#!/usr/bin/env python3
"""Compile data/seed.tsv into a C header the firmware links straight into flash.

Keeping the deck as a generated header rather than a filesystem image means the device
needs no SPIFFS/LittleFS partition and no upload step beyond the firmware itself. On the
ESP32 string literals live in flash and are readable through ordinary pointers, so there
is no PROGMEM dance to do -- that is an AVR concern.

The id column is what per-entry progress is keyed off, so ids are emitted as-is and never
renumbered; the array index is deliberately not used as an identity.
"""
import csv
import sys
from pathlib import Path

TYPES = {"word": 0, "structure": 1}
LEVELS = {"A2": 0, "B1": 1, "B2": 2}


def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main(src, dst):
    rows = list(csv.DictReader(Path(src).read_text(encoding="utf-8").splitlines(),
                              delimiter="\t"))
    seen = set()
    for r in rows:
        i = int(r["id"])
        if i in seen:
            sys.exit(f"duplicate id {i} -- ids key the saved progress and must be unique")
        seen.add(i)

    out = [
        "// Generated by tools/gen_deck.py from data/seed.tsv -- do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "enum EntryType : uint8_t { TYPE_WORD = 0, TYPE_STRUCTURE = 1 };",
        "enum EntryLevel : uint8_t { LEVEL_A2 = 0, LEVEL_B1 = 1, LEVEL_B2 = 2 };",
        "",
        "struct Entry {",
        "  uint16_t id;        // stable across edits; saved progress is keyed off it",
        "  uint8_t  type;",
        "  uint8_t  level;",
        "  const char *front;  // English term or pattern",
        "  const char *back;   // Vietnamese meaning",
        "  const char *example;",
        "};",
        "",
        f"static const uint16_t DECK_COUNT = {len(rows)};",
        "",
        "static const Entry DECK[DECK_COUNT] = {",
    ]
    for r in rows:
        out.append(
            f'  {{{r["id"]}, {TYPES[r["type"]]}, {LEVELS[r["level"]]}, '
            f'"{escape(r["front"])}", "{escape(r["back"])}", "{escape(r["example"])}"}},'
        )
    out += ["};", ""]
    Path(dst).write_text("\n".join(out), encoding="utf-8")

    words = sum(1 for r in rows if r["type"] == "word")
    print(f"{len(rows)} entries ({words} words, {len(rows) - words} structures) -> {dst}")
    print(f"  max id {max(seen)}, longest front {max(len(r['front']) for r in rows)} chars, "
          f"longest back {max(len(r['back']) for r in rows)} chars")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "data/seed.tsv",
         sys.argv[2] if len(sys.argv) > 2 else "include/deck.h")
