#!/usr/bin/env python3
"""Convert a TTF into the VLW bitmap-font format TFT_eSPI loads for smooth text.

TFT_eSPI's own converter is a Processing sketch, which means installing a Java IDE to
produce one binary file. This does the same job from the command line, so regenerating a
font after changing a size or a character set is one command inside the normal build.

Layout of a .vlw file, all integers big-endian int32:

    header, 6 ints (24 bytes)
        glyph count
        encoder version (11)
        yAdvance -- line height
        unused
        ascent   -- top of "d"
        descent  -- bottom of "p"

    metrics, 7 ints per glyph (28 bytes each), in file order
        unicode code point
        bitmap height
        bitmap width
        x advance
        dY -- baseline to top of bitmap, positive upwards
        dX -- left side bearing
        unused

    bitmaps, concatenated in the same order, one byte of alpha per pixel

TFT_eSPI derives its own maxAscent/maxDescent by scanning the per-glyph dY, so the header
ascent/descent are informational; the per-glyph values are what position the text. Space
is special-cased by the library: it needs a correct x advance but no bitmap.
"""
import argparse
import struct
import sys
import unicodedata
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

VLW_VERSION = 11


def vietnamese_charset():
    """Every precomposed Vietnamese letter, both cases, plus đ."""
    bases = "aăâeêioôơuưy"
    tones = ["", "̀", "́", "̃", "̉", "̣"]
    out = {unicodedata.normalize("NFC", b + t) for b in bases for t in tones}
    out |= {c.upper() for c in out}
    return out | {"đ", "Đ"}


def charset(name):
    ascii_printable = {chr(c) for c in range(0x20, 0x7F)}
    if name == "ascii":
        return ascii_printable
    if name == "vietnamese":
        return ascii_printable | vietnamese_charset()
    raise SystemExit(f"unknown charset {name!r}; use ascii or vietnamese")


def render_glyph(font, ch):
    """Bitmap plus baseline-relative metrics for one character.

    Pillow's "ls" anchor puts the origin on the baseline at the left edge, so y comes back
    negative above the baseline -- exactly the frame VLW's dY uses, once negated.
    """
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
    width, height = x1 - x0, y1 - y0
    advance = round(font.getlength(ch))

    if width <= 0 or height <= 0:  # space and friends carry advance but no ink
        return b"", 0, 0, advance, 0, 0

    image = Image.new("L", (width, height), 0)
    ImageDraw.Draw(image).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
    return image.tobytes(), width, height, advance, -y0, x0


def build(ttf, size, chars, index=0):
    font = ImageFont.truetype(ttf, size, index=index)
    glyphs = []
    for ch in sorted(chars, key=ord):
        bitmap, w, h, advance, dy, dx = render_glyph(font, ch)
        glyphs.append((ord(ch), h, w, advance, dy, dx, bitmap))

    # The library's own semantics: ascent is the top of "d", descent the bottom of "p".
    ascent = max((g[4] for g in glyphs if g[0] == ord("d")), default=size)
    descent = max((g[1] - g[4] for g in glyphs if g[0] == ord("p")), default=0)
    y_advance = font.getmetrics()[0] + font.getmetrics()[1]

    out = bytearray()
    out += struct.pack(">6i", len(glyphs), VLW_VERSION, y_advance, 0, ascent, descent)
    for code, h, w, advance, dy, dx, _ in glyphs:
        out += struct.pack(">7i", code, h, w, advance, dy, dx, 0)
    for *_, bitmap in glyphs:
        out += bitmap
    return bytes(out), glyphs


def write_header(path, name, blob):
    """Emit the font as a PROGMEM array so no filesystem is needed on the device."""
    lines = [
        "// Generated by tools/ttf2vlw.py -- do not edit.",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
        f"// {len(blob)} bytes",
        f"const uint8_t {name}[] PROGMEM = {{",
    ]
    for i in range(0, len(blob), 16):
        lines.append("  " + "".join(f"0x{b:02X}, " for b in blob[i:i + 16]).rstrip())
    lines += ["};", ""]
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def write_preview(path, ttf, size, index=0):
    """A PNG of real sample text, to judge legibility before spending a flash cycle."""
    font = ImageFont.truetype(ttf, size, index=index)
    samples = [
        "afford  approach  whether",
        "có đủ khả năng (tài chính)",
        "đã quen với việc  cuối cùng",
        "ĐẦU TIÊN  Ưu  Ổn  Ậ  Ỹ",
    ]
    pad, gap = 8, 4
    height = pad * 2 + len(samples) * (size + gap)
    image = Image.new("L", (240, height), 0)
    draw = ImageDraw.Draw(image)
    for i, line in enumerate(samples):
        draw.text((pad, pad + i * (size + gap)), line, font=font, fill=255)
    image.save(path)
    return image.size


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("ttf")
    ap.add_argument("--size", type=int, required=True)
    ap.add_argument("--charset", default="vietnamese", choices=["ascii", "vietnamese"])
    ap.add_argument("--index", type=int, default=0, help="face index inside a .ttc")
    ap.add_argument("--out-vlw")
    ap.add_argument("--out-header")
    ap.add_argument("--name", default="font")
    ap.add_argument("--preview")
    args = ap.parse_args()

    chars = charset(args.charset)
    blob, glyphs = build(args.ttf, args.size, chars, args.index)

    tallest = max(glyphs, key=lambda g: g[4])
    print(f"{len(glyphs)} glyphs, {len(blob)} bytes ({len(blob)/1024:.1f} KB)")
    print(f"  bitmap data {sum(len(g[6]) for g in glyphs)/1024:.1f} KB, "
          f"metrics {len(glyphs)*28/1024:.1f} KB")
    print(f"  tallest glyph above baseline: {chr(tallest[0])!r} at dY={tallest[4]}")

    if args.out_vlw:
        Path(args.out_vlw).write_bytes(blob)
        print(f"  -> {args.out_vlw}")
    if args.out_header:
        write_header(args.out_header, args.name, blob)
        print(f"  -> {args.out_header}")
    if args.preview:
        print(f"  -> {args.preview} {write_preview(args.preview, args.ttf, args.size, args.index)}")
